version: '3'

services:
  db:
    image: mysql:8.0-debian
    restart: always
    volumes:
      - ./portfolio-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

#volumes:
#  portfolio:
#    external: true